name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  code_checks:
    name: Code Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install dependencies
        run: npm ci

      - name: Lint (ESLint)
        run: npm run lint:check

      - name: Check formatting (Prettier)
        run: npm run prettier:check

      - name: Build TypeScript
        run: npm run build

      - name: Run Tests
        run: npm run test
